[model]
name = "elasticity"
dim = 2
2D_assumption = "plane_strain"

[mesh]
msh_file = "mesh.msh"

[mesh.physical_groups]
left  = 5
right = 6

[mechanical]
E = 30e9
nu = 0.3

[loading]
[loading.u_imp_max]
left  = [  0, 0]
right = [nan, 0.1]

[end]
criterion = "t"
t_max = 10

[postprocess]

[postprocess.probes]
displacement= [
    [ 0, 0.5, 0],
    [10, 0.5, 0],
]
