[model]
name = "elasticity"
dim = 2
2D_assumption = "plane_strain"

[mesh]
msh_file = "mesh.msh"

[mesh.physical_groups]
left  = 5
right = 6

[mechanical]
E = 30e9
nu = 0.00

[loading]
dt = 0.1

[loading.u_imp_max]
left = [0, 0]
right = [0.1, 0]

[postprocess]
# TODO fields = ["strain", "stress"]
reaction_forces = ["left", "right"]

[postprocess.probes]
displacement= [
    [ 0, 0.5, 0],
    [10, 0.5, 0],
]
