model = "elasticity"

[mesh]
dim = 2
msh_file = "mesh.msh"

[mesh.physical_groups]
bot = 7
top = 8
clamp = 9

[mechanical]
mu = 20e9
lambda = 10e9

[loading]
clamp_0 = 0.0
bot_1 = -1e-4
top_1 =  1e-4

