[model]
name = "elasticity"
dim = 3

[mesh]
msh_file = "mesh.msh"

[mesh.physical_groups]
bot = 13
top = 14

[mechanical]
E = 30e9
nu = 0.3

[loading]
dt = 0.1

[loading.u_imp_max]
bot = [0, 0, 0]
top = [0, 1e-3, 0]

