model = "elasticity"

[mesh]
dim = 2
msh_file = "mesh.msh"

[mesh.physical_groups]
left  = 5
right = 6

[mechanical]
mu = 10e9
lambda = 20e9

[loading]
left_0 = 0
left_1 = 0
# right_0 = 1e-3
right_1 = 1e-3

