[model]
name = "elasticity"
dim = 2
2D_assumption = "plane_strain"

[mesh]
msh_file = "mesh.msh"

[mesh.physical_groups]
left  = 5
right = 6

[mechanical]
E = 30e9
nu = 0.3

[loading]
dt = 0.05
constraint = "max_strain_inc"
l0 = 0.01
dtau = 1e-3

[loading.u_imp_max]
left_0 = 0
left_1 = 0
right_0 = 0.1
right_1 = 0

[postprocess.probes]
displacement= [
    [ 0, 0.5, 0],
    [10, 0.5, 0],
]
