[model]
name = "elasticity"
dim = 2
2D_assumption = "plane_strain"

[mesh]
msh_file = "mesh.msh"

[mesh.physical_groups]
left  = 5
right = 6

[mechanical]
E = 30e9
nu = 0.0

[loading]
constraint = "time"
# constraint = "max_strain_inc"
# l0 = 0.01
# dtau = 1e-3

[loading.u_imp_max]
left = [0, 0]
right = [0.1, 0]

[end]
criterion = "t"
t_max = 20

[postprocess.probes]
displacement= [
    [ 0, 0.5, 0],
    [10, 0.5, 0],
]

