[model]
name = "elasticity"
dim = 2
2D_assumption = "plane_strain"

[mesh]
msh_file = "mesh.msh"

[mesh.physical_groups]
bot = 11
top = 12
crack = 13

[numerical]
utol = 1e-9

[mechanical]
E = 1
nu = 0.3

[loading]
[loading.nodal_displacement]
lock_point.x = [0, -0.5, 0]
lock_point.u = [0, 0]
[loading.u_imp_max]
bot = [nan, 0]
[loading.f_imp_max]
top = [0, 1]

[end]
criterion = "t"
t_max = 1

[postprocess]
reaction_forces = ["bot", "top"]
[postprocess.probes]
displacement= [
    [-0.5, 0, 0],
    [ 0.5, 0, 0],
]
[postprocess.SIFs]
crack_tip = [0.05, 0]
R_int = {R_int}
R_ext = {R_ext}
crack_growth_angle = 0
