[model]
name = "fracture"
dim = 2
2D_assumption = "plane_strain"
model = "Foc4-Foc4"

[mesh]
msh_file = "mesh.msh"

[mesh.physical_groups]
left_bot = 9
left_top = 10
# non-crackable_1 = 9
# non-crackable_2 = 10
crack = 4

[numerical]
nl_solver = "tao" # Using a TAO solver from PETSc (SNES does not converge)
utol = 1e-6
atol = 1e-6
max_iter = 100_000
alpha_res = 1e-12

[mechanical]
E = 1e12
nu = 0.3
# Parameters of the Foc4 model
ell = 1e-4
Gc = 1
D2 = 0
P2 = 0
D4 = 0.99
P4 = 0 # 0.7853981633974483
# The crack is expected to go at +pi/4 or -pi/4

[loading]
dl = 0.01

[loading.u_imp_max]
left_bot = [0, -1e-6]
left_top = [0, +1e-6]

[end]
criterion = "elastic_energy_drop"
drop = 0.01

[postprocess]
reaction_forces = ["left_bot", "left_top"]
[postprocess.probes]
displacement= [
    [0, 0, 0],
    [0, 1e-3, 0],
]

