[model]
name = "fracture"
dim = 2
2D_assumption = "plane_stress"
model = "AT1"

[mesh]
msh_file = "mesh.msh"

[mesh.physical_groups]
bot = 7
top = 8
left_bot = 9
left_top = 10
crack = 12
non-crackable_1 = 7
non-crackable_2 = 8

[numerical]
utol = 1e-6
atol = 1e-5
max_iter = 100
alpha_res = 1e-6

[mechanical]
E = 1.9e9
nu = 0.34
Gc = 1 # 4.5e3
ell = 1e-3 # 0.06e-3

[loading]
dt = 0.01

[loading.u_imp_max]
# Clamp
left_bot = [0.0, nan]
# Bot
bot = [nan, -2e-6]
# Top
top = [nan,  2e-6]

