[model]
name = "elasticity"
dim = 2
2D_assumption = "plane_stress"

[mesh]
msh_file = "mesh.msh"

[mesh.physical_groups]
bot = 7
top = 8
left_bot = 9
left_top = 10

[mechanical]
E = 1.9e9
nu = 0.34

[loading]
# Clamp
left_bot_0 =  0.0
# Bot
left_bot_1 = -1e-4
bot_1      = -1e-4
# Top
left_top_1 =  1e-4
top_1      =  1e-4

