[model]
name = "elasticity"
dim = 2
2D_assumption = "plane_strain"

[mesh]
msh_file = "mesh.msh"

[mesh.physical_groups]
bot  = 5
right = 6
top  = 7
left = 8

[mechanical]
E = 30e9
nu = 0.3

[loading]
[loading.nodal_displacement]
clamp.x  = [0, 0, 0]
clamp.u  = [0, 0]
rotat.x  = [0, 1, 0]
rotat.u  = [0, nan]
[loading.thermal_load]
thermal_expansion_coeff = 5e-5
dT = "100*Heaviside(10*t - x[0], 0)"
# Note that t is in fact the load factor.
# It is increment by an increment dl each load step.
# When dl is not specified, it is equal to t/t_max.

[end]
criterion = "t"
t_max = 10
