[model]
name = "fracture"
dim = 2
2D_assumption = "plane_stress"
model = "AT1"

[mesh]
msh_file = "mesh.msh"

[mesh.physical_groups]
bot = 9
top = 10
crack = 12

[numerical]
utol = 1e-6
atol = 1e-3
max_iter = 10_000
alpha_res = 1e-6

[mechanical]
E = 3e9
nu = 0.4
Gc = 380
ell = 2e-3 # Real value 0.3e-3

[loading]
[loading.u_imp_max]
# Clamp
bot = [0, 0]
# Top
top = [nan, 2e-3]

[end]
criterion = "t"
t_max = 100
