[model]
name = "fracture"
dim = 2
2D_assumption = "plane_stress"
model = "AT1"

[mesh]
msh_file = "mesh.msh"

[mesh.physical_groups]
crack = 13
non-crackable_1 = 14
non-crackable_2 = 15
bot_pin = 14
top_pin = 15

[numerical]
atol = 1e-4
max_iter = 1000
alpha_res = 1e-12

[mechanical]
E = 3e9
nu = 0.4
Gc = 380
ell = 3e-3

[loading]
t_max = 50

[loading.u_incs]
bot_pin_0 = 0
bot_pin_1 = -5e-5
top_pin_0 = 0
top_pin_1 =  5e-5
