[model]
name = "elasticity"
dim = 2
2D_assumption = "plane_strain"
model = "AT1"

[mesh]
msh_file = "mesh.msh"

[mesh.physical_groups]
bot = 11
top = 12
crack = 13

[numerical]
utol = 1e-9

[mechanical]
E = 230.77e9
nu = 0.43

[loading]
[loading.nodal_displacement]
lock_point.x = [0, 0, 0]
lock_point.u = [0, 0]
[loading.u_imp_max]
bot = [nan, 0]
[loading.f_imp_max]
top = [0, 1e9]

[end]
criterion = "t"
t_max = 1

[postprocess]
reaction_forces = ["bot", "top"]
[postprocess.energy_release_rate]
crack_tip = [0.25e-3, 0.5e-3, 0]
R_int = 1e-5
R_ext = 1e-4
crack_growth_angle = 0

